import Head from "next/head";
import React from "react";
import Footer from "../Components/Shared/Footer/Footer";
import Navbar from "../Components/Shared/Navbar/Navbar";
import BookIndex from "../Components/Book/BookIndex";
import authCheck from "../Components/Context/authCheck";
import adminCheck from "../Components/Context/adminCheck";

const book = () => {
  return (
    <div>
      <Head>
        <title>How To Book -Rescue Reach</title>
        <meta name="description" content="Generated by Ambulance Service" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <BookIndex />

      <Footer />
    </div>
  );
};

export default authCheck(book);
