import Head from "next/head";
import React from "react";
import Navbar from "../Components/Shared/Navbar/Navbar";
import LocationTrackIndex from "../Components/LocationTrack/LocationTrackIndex";
import Footer from "../Components/Shared/Footer/Footer";
import authCheck from "../Components/Context/authCheck";

const locationTrack = () => {
  return (
    <div>
      <Head>
        <title>Rescue Reach</title>
        <meta name="description" content="Generated by Ambulance Service" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <LocationTrackIndex />
      <Footer />
    </div>
  );
};

export default authCheck(locationTrack);
